# Generated by Django 4.0.3 on 2022-03-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carPlates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_plate',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
